# [Choice] Node.js version: 14, 12, 10
FROM mcr.microsoft.com/devcontainers/javascript-node:20

RUN sudo -u node npm install -g @quasar/cli

# RUN npm install
# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>